MMCREvents.server(event => {
    const api = event.getAPI()
    const structure = event.createStructure("mmcr:industrial_imbuement")
        .pattern("XXAXX", "XBBBX", "XBBBX", "XBBBX", "XXXXX")
        .pattern("XXXXX", "B D B", "B   B", "B   B", "XXXXX")
        .pattern("EXXXF", "BDGDB", "B H B", "B   B", "XXXXX")
        .pattern("XXXXX", "B D B", "B   B", "B   B", "XXXXX")
        .pattern("XXCXX", "XBBBX", "XBBBX", "XBBBX", "XXXXX")
        .set('X', api.block('ars_nouveau:smooth_sourcestone_large_bricks'))
        .set('A', api.anyOfSourceInput())
        .set('B', api.block('mekanism:structural_glass'))
        .set('D', api.state('ars_nouveau:arcane_platform[facing=up]'))
        .set('E', api.anyOfItemOutput())
        .set('F', api.anyOfItemInput())
        .set('G', api.block('ars_nouveau:arcane_core'))
        .set('H', api.block('ars_nouveau:imbuement_chamber'))
        .controller('C')
        .build()
})
