#机器升级插件相关设置
[Upgrades]

	[Upgrades.basic_batch_upgrade]
		#加成数值 (如增加并行处理数量、增加槽位堆叠容量)。
		# Default: 0.5
		# Range: 0.0 ~ 10000.0
		value = 0.5
		#单台机器能放入的这种插件的最大数量。
		# Default: 16
		# Range: 1 ~ 64
		maxLimit = 16
		#每放入一个插件，机器增加的额外耗电比例 (如 0.05 代表增加 5% 耗电)。
		# Default: 0.05000000074505806
		# Range: 0.0 ~ 100.0
		energyPenalty = 0.05000000074505806

	[Upgrades.crystalline_batch_upgrade]
		#加成数值 (如增加并行处理数量、增加槽位堆叠容量)。
		# Default: 2.0
		# Range: 0.0 ~ 10000.0
		value = 2.0
		#单台机器能放入的这种插件的最大数量。
		# Default: 8
		# Range: 1 ~ 64
		maxLimit = 8
		#每放入一个插件，机器增加的额外耗电比例 (如 0.05 代表增加 5% 耗电)。
		# Default: 0.10000000149011612
		# Range: 0.0 ~ 100.0
		energyPenalty = 0.10000000149011612

	[Upgrades.stellar_batch_upgrade]
		#加成数值 (如增加并行处理数量、增加槽位堆叠容量)。
		# Default: 8.0
		# Range: 0.0 ~ 10000.0
		value = 8.0
		#单台机器能放入的这种插件的最大数量。
		# Default: 4
		# Range: 1 ~ 64
		maxLimit = 4
		#每放入一个插件，机器增加的额外耗电比例 (如 0.05 代表增加 5% 耗电)。
		# Default: 0.20000000298023224
		# Range: 0.0 ~ 100.0
		energyPenalty = 0.20000000298023224

	[Upgrades.basic_stack_upgrade]
		#加成数值 (如增加并行处理数量、增加槽位堆叠容量)。
		# Default: 16.0
		# Range: 0.0 ~ 10000.0
		value = 16.0
		#单台机器能放入的这种插件的最大数量。
		# Default: 16
		# Range: 1 ~ 64
		maxLimit = 16
		#每放入一个插件，机器增加的额外耗电比例 (如 0.05 代表增加 5% 耗电)。
		# Default: 0.009999999776482582
		# Range: 0.0 ~ 100.0
		energyPenalty = 0.009999999776482582

	[Upgrades.crystalline_stack_upgrade]
		#加成数值 (如增加并行处理数量、增加槽位堆叠容量)。
		# Default: 64.0
		# Range: 0.0 ~ 10000.0
		value = 64.0
		#单台机器能放入的这种插件的最大数量。
		# Default: 8
		# Range: 1 ~ 64
		maxLimit = 8
		#每放入一个插件，机器增加的额外耗电比例 (如 0.05 代表增加 5% 耗电)。
		# Default: 0.019999999552965164
		# Range: 0.0 ~ 100.0
		energyPenalty = 0.019999999552965164

	[Upgrades.stellar_stack_upgrade]
		#加成数值 (如增加并行处理数量、增加槽位堆叠容量)。
		# Default: 256.0
		# Range: 0.0 ~ 10000.0
		value = 256.0
		#单台机器能放入的这种插件的最大数量。
		# Default: 4
		# Range: 1 ~ 64
		maxLimit = 4
		#每放入一个插件，机器增加的额外耗电比例 (如 0.05 代表增加 5% 耗电)。
		# Default: 0.03999999910593033
		# Range: 0.0 ~ 100.0
		energyPenalty = 0.03999999910593033

#不同机器对插件效果的吸收效率 (1.0 代表 100%)。
#举例如下：如果设为 0.5，则插件提供的能力和带来的额外耗电都会直接减半。
[Utilization]

	[Utilization.SAG_MILL]
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		stackUtilization = 1.0
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		batchUtilization = 1.0

	[Utilization.ALLOY_SMELTER]
		# Default: 3.0
		# Range: 0.0 ~ 100.0
		stackUtilization = 3.0
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		batchUtilization = 1.0

	[Utilization.VAT]
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		stackUtilization = 1.0
		# Default: 1.5
		# Range: 0.0 ~ 100.0
		batchUtilization = 1.5

	[Utilization.SPAWNER]
		# Default: 0.25
		# Range: 0.0 ~ 100.0
		batchUtilization = 0.25

	[Utilization.DRAIN]
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		stackUtilization = 1.0
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		batchUtilization = 1.0

	[Utilization.SOUL_BINDER]
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		stackUtilization = 1.0
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		batchUtilization = 1.0

	[Utilization.SLICER]
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		stackUtilization = 1.0
		# Default: 1.0
		# Range: 0.0 ~ 100.0
		batchUtilization = 1.0
